places_like_to_visit = ['Huatuco','Grecia','Manchester','Los cabos','Avellaneda']
print(places_like_to_visit)
print(sorted(places_like_to_visit))
print(places_like_to_visit)
print(sorted(places_like_to_visit,reverse=True))
print(places_like_to_visit)
print(sorted(places_like_to_visit,reverse=True))
print(places_like_to_visit)
print("Using sort method ¬¬")
places_like_to_visit.sort()
print(places_like_to_visit)
